/**
 * 操作参数名的中文显示词典。
 *
 * 重要：本词典只用于「界面显示」，不会修改 Operation.args[].name。
 * 之所以不在源码里直接改名，是因为参数名同时是：
 *   1) Node.js API 按名传参（args 对象写法）的键；
 *   2) 参数校验报错信息的组成部分；
 *   3) 上游自动化测试的断言依据。
 * 直接改名会破坏这些公开契约，因此改为在渲染层做一层查表。
 *
 * 本文件由 tools/gen_argname_zh.py 生成，请勿手工编辑。
 */

export default {
    "1st (left-hand) cipher rotor": "第一(左手)密码转子",
    "1st (left-hand) control rotor": "第一(左手)控制转子",
    "1st (left-hand) index rotor": "第一(左)分度转子",
    "1st (left-hand) rotor": "第一(左)转子",
    "1st cipher rotor initial value": "第一密码转子初始值",
    "1st cipher rotor reversed": "第一密码反转子",
    "1st control rotor initial value": "第一控制转子初始值",
    "1st control rotor reversed": "第一控制反转子",
    "1st index rotor initial value": "第一分度转子初始值",
    "1st rotor initial value": "第一转子初始值",
    "1st rotor reversed": "第一反转子",
    "1st rotor ring setting": "第一转子环设置",
    "2nd cipher rotor": "第二密码转子",
    "2nd cipher rotor initial value": "第二密码转子初始值",
    "2nd cipher rotor reversed": "第二密码反转子",
    "2nd control rotor": "第二控制转子",
    "2nd control rotor initial value": "第二控制转子初值",
    "2nd control rotor reversed": "第二控制反转子",
    "2nd index rotor": "第二分度转子",
    "2nd index rotor initial value": "第二分度转子初始值",
    "2nd rotor": "第二转子",
    "2nd rotor initial value": "第二转子初始值",
    "2nd rotor reversed": "第二反转子",
    "2nd rotor ring setting": "第二转子环设置",
    "3rd (middle) cipher rotor": "第三(中)密码转子",
    "3rd (middle) control rotor": "第三(中)控制转子",
    "3rd (middle) index rotor": "第三(中)分度转子",
    "3rd (middle) rotor": "第三(中间)转子",
    "3rd cipher rotor initial value": "第三个密码转子初始值",
    "3rd cipher rotor reversed": "第三个密码反转子",
    "3rd control rotor initial value": "第三控制转子初始值",
    "3rd control rotor reversed": "第三个控制反转子",
    "3rd index rotor initial value": "第三分度转子初始值",
    "3rd rotor initial value": "第三转子初始值",
    "3rd rotor reversed": "第三反转子",
    "3rd rotor ring setting": "第三转子环设置",
    "4th (static) rotor": "第四(静)转子",
    "4th cipher rotor": "第四密码转子",
    "4th cipher rotor initial value": "第四密码转子初始值",
    "4th cipher rotor reversed": "第四密码反转子",
    "4th control rotor": "第四控制转子",
    "4th control rotor initial value": "第四控制转子初值",
    "4th control rotor reversed": "第四控制反转子",
    "4th index rotor": "第四分度转子",
    "4th index rotor initial value": "第四分度转子初值",
    "4th rotor": "第四转子",
    "4th rotor initial value": "第四转子初始值",
    "4th rotor reversed": "第四反转子",
    "4th rotor ring setting": "第四转子环设置",
    "5th (right-hand) cipher rotor": "第五(右手)密码转子",
    "5th (right-hand) control rotor": "第五(右手)控制转子",
    "5th (right-hand) index rotor": "第五(右手)分度转子",
    "5th (right-hand, static) rotor": "第五(右手，静)转子",
    "5th cipher rotor initial value": "第五密码转子初始值",
    "5th cipher rotor reversed": "第五密码反转子",
    "5th control rotor initial value": "第五控制转子初值",
    "5th control rotor reversed": "第五控制反转子",
    "5th index rotor initial value": "第五分度转子初值",
    "5th rotor initial value": "第五转子初始值",
    "5th rotor reversed": "第五反转子",
    "5th rotor ring setting": "第五转子环设置",
    "^ and $ match at newlines": "^ 和 $ 匹配换行",
    "Additional Authenticated Data": "附加认证数据",
    "Algorithm": "算法",
    "All hashes": "全部哈希",
    "All-zero group char": "全零组字符",
    "Allow large queries": "允许大型查询",
    "Alpha": "透明度",
    "Alphabet": "字母",
    "Alphabet size (k)": "字母表大小 (k)",
    "Amount": "数量",
    "Answer Data Only": "仅回答数据",
    "Applications": "应用",
    "Apply to each line": "应用于每一行",
    "Architecture": "架构",
    "Archives": "档案",
    "Associated Data": "关联数据",
    "Astral support": "增补平面支持",
    "Attempt to be context aware": "尝试感知上下文",
    "Audio": "音频",
    "Autoconvert URLs to links": "自动将 URL 转为链接",
    "Autocrop": "自动裁剪",
    "Autocrop keep border (px)": "自动裁剪边框 (px)",
    "Autocrop tolerance (%)": "自动裁剪宽容度 (%)",
    "Axis": "轴",
    "Base": "基数",
    "Bit length": "位长度",
    "Bit mode": "bit 模式",
    "Block mode": "块模式",
    "Block size (100s of kb)": "块大小（单位：100 KB）",
    "Blocksize": "块大小",
    "Blue": "蓝(Blue)",
    "Box Height": "Box 高度",
    "Brightness": "亮度",
    "Buffer expansion type": "缓冲区扩展类型",
    "Built in formats": "内置格式",
    "Built in regexes": "内置正则表达式",
    "By": "按",
    "Byte Length": "字节长度",
    "Bytes per line": "每行字节数",
    "Camel bonus": "驼峰加分",
    "Capacity": "容量",
    "Carriage returns (\\r)": "回车 (\\r)",
    "Carry through": "进位传递",
    "Case insensitive": "不区分大小写",
    "Case sensitive matching": "区分大小写匹配",
    "Cell delimiter": "单元格分隔符",
    "Cell delimiters": "单元格分隔符",
    "Character": "字符",
    "Ciphertext": "密文",
    "Cisco style": "思科风格",
    "Code length": "代码长度",
    "Code Segment (CS)": "代码段 (CS)",
    "Colon delimiter": "冒号分隔符",
    "Colour": "颜色",
    "Colour Pattern #1": "颜色图案 #1",
    "Colour Pattern #2": "颜色图案 #2",
    "Colour Pattern #3": "颜色图案 #3",
    "Colour Pattern #4": "颜色图案 #4",
    "Comment": "注释",
    "Comment (optional)": "注释（可选）",
    "Compatibility": "兼容性",
    "Compression Format": "压缩格式",
    "Compression method": "压缩方法",
    "Compression Mode": "压缩模式",
    "Compression type": "压缩类型",
    "Contrast": "对比度",
    "Convert": "转换",
    "Convert all characters": "转换所有字符",
    "Convert to": "转换为",
    "Convert to Signed": "转换为有符号",
    "Counter": "计数器",
    "Crib (known plaintext string or regex)": "Crib（已知明文字符串或正则表达式）",
    "Crib (known plaintext string)": "Crib（已知明文字符串）",
    "Crib offset": "Crib 偏移",
    "Crypto grade": "加密等级",
    "CSS selector": "CSS 选择器",
    "Dash delimiter": "-分隔符",
    "Data format": "数据格式",
    "Days": "天",
    "Decode Option": "解码选项",
    "Decompressed size": "解压后大小",
    "Deletion cost": "删除成本",
    "Delimiter": "分隔符",
    "Depth": "深度",
    "Diff by": "比较方式",
    "Digest length": "摘要长度",
    "Direction": "方向",
    "Disable DNSSEC validation": "禁用DNSSEC验证",
    "Display count": "显示数",
    "Display total": "显示总数",
    "Display Total": "显示总数",
    "Documents": "文档",
    "Dot matches all": "点号匹配全部字符",
    "Draw bin edges": "绘制桶边",
    "Draw empty hexagons within data boundaries": "在数据边界内绘制空六边形",
    "Draw hexagon edges": "绘制六边形边缘",
    "Draw radius": "绘制半径",
    "Drop every": "每隔 N 个丢弃",
    "ECDSA Private Key (PEM)": "ECDSA 私钥 (PEM)",
    "ECDSA Public Key (PEM)": "ECDSA 公钥 (PEM)",
    "Email (optional)": "电子邮件(可选)",
    "Enable syntax highlighting": "启用语法高亮显示",
    "Encode all chars": "编码所有字符",
    "Encode all special chars": "对所有特殊字符进行编码",
    "Encode Option": "编码选项",
    "Encode or Decode": "编码或解码",
    "Encoded hash": "哈希编码",
    "Encoding": "编码",
    "Encryption algorithm": "加密算法",
    "Encryption Scheme": "加密方案",
    "Endianness": "字节顺序",
    "Enumerate IP addresses": "枚举 IP 地址",
    "Epoch offset (T0)": "纪元偏移 (T0)",
    "Error correction": "容错率",
    "ES6 compatible": "兼容ES6",
    "Escape ://": "转义 ://",
    "Escape dots": "转义点号",
    "Escape http": "转义 http",
    "Escape level": "转义级别",
    "Escape quote": "转义引号",
    "Extensive language support": "广泛的语言支持",
    "Extract mode": "提取模式",
    "Extractor": "提取器",
    "Fast Step": "快步进",
    "Field delimiter": "字段分隔符",
    "File Path Delimiter": "文件路径分隔符",
    "Filename": "文件名",
    "Filename (optional)": "文件名（可选）",
    "Filter type": "过滤类型",
    "Find": "查找",
    "First letter bonus": "首字母加分",
    "Font face": "字体",
    "Force Valid JSON": "强制为有效 JSON",
    "Form feeds (\\f)": "换页 (\\f)",
    "Format": "格式",
    "Format options": "格式选项",
    "Formatted": "格式化",
    "Full stops": "句号",
    "Global match": "全局匹配",
    "Global matching": "全匹配",
    "Granularity": "颗粒度",
    "Green": "绿(Green)",
    "Hash character length": "哈希字符长度",
    "Hash length (bytes)": "哈希长度 (字节)",
    "Hashing function": "哈希函数",
    "Header": "头部",
    "Header string": "标题字符串",
    "Headers": "头部",
    "Height": "高度",
    "Horizontal align": "水平对齐",
    "Hours": "小时",
    "Hue": "色调",
    "Human-Readable Part (HRP)": "可读部分 (HRP)",
    "Ignore case": "忽略大小写",
    "Ignore errors": "忽略错误",
    "Ignore failed extractions": "忽略失败的提取",
    "Ignore ranges": "忽略范围",
    "Ignore whitespace": "忽略空白",
    "Image Format": "图片格式",
    "Images": "图片",
    "Include Alpha": "包括 Alpha",
    "Include comments": "包含 comments",
    "Include comments array": "包含 comments 数组",
    "Include Compass Directions": "包括罗盘方向",
    "Include delimiter": "包含分隔符",
    "Include file checksum": "包含文件校验和",
    "Include final length": "包括最终长度",
    "Include IV in output": "输出中包含 IV",
    "Include Metadata": "包含元数据",
    "Include names": "包括名字",
    "Include network info": "包括网络信息",
    "Include tokens array": "包括 tokens 数组",
    "Indent string": "缩进字符串",
    "Info": "信息",
    "Initial output buffer size": "初始输出缓冲区大小",
    "Initialization": "初始化",
    "Input": "输入",
    "Input Delimiter": "输入分隔符",
    "Input format": "输入格式",
    "Input Format": "输入格式",
    "Input format string": "输入格式字符串",
    "Input timezone": "输入时区",
    "Input type": "输入类型",
    "Input Type": "输入类型",
    "Input units": "输入单位",
    "Insertion cost": "插入成本",
    "Intensive mode": "强化模式",
    "Internationalised domain name": "国际化域名",
    "Interval (T1)": "时间间隔 (T1)",
    "Invert condition": "反转条件",
    "Invert match": "反向匹配",
    "Invert Translation": "反向翻译",
    "IPv6 interface ID": "IPv6 接口ID",
    "ITA2 Format": "ITA2 格式",
    "Item delimiter": "项分隔符",
    "Iterations": "迭代",
    "Iterations (N)": "迭代 (N)",
    "IV from input": "IV 取自输入",
    "Join delimiter": "连接分隔符",
    "JPEG Quality": "JPEG 质量",
    "JSON compatible": "兼容JSON",
    "K Rack Option": "K Rack 选项",
    "Keep extra characters": "保留多余字符",
    "Key length": "密钥长度",
    "Key length (n)": "密钥长度 (n)",
    "Key meshing mode": "密钥混洗模式",
    "Key Password": "密钥密码",
    "Key size": "密钥长度",
    "Key type": "密钥类型",
    "Key wrapping": "密钥包装",
    "Keyword": "关键字",
    "L (number of output octets)": "输出字节数",
    "Label name": "标签名称",
    "Language": "语言",
    "Leading letter penalty": "首字母惩罚",
    "Left-hand rotor": "左转子",
    "Left-hand rotor initial value": "左转子初始值",
    "Left-hand rotor ring setting": "左转子环设置",
    "Left-most (4th) rotor": "最左侧（第 4）转子",
    "Left-most rotor initial value": "最左侧转子初始值",
    "Left-most rotor ring setting": "最左侧转子环设置",
    "Length": "长度",
    "Length (bits)": "长度（位）",
    "Length in": "长度单位",
    "Length size": "长度字段大小",
    "Letter delimiter": "字母分隔符",
    "Levels": "等级",
    "Lightness": "明度",
    "Limitation": "限制",
    "Line feeds (\\n)": "换行 (\\n)",
    "Line Width": "行宽",
    "Location info": "位置信息",
    "MAC length": "MAC 长度",
    "Main rotors": "主转子",
    "Maintain aspect ratio": "保持纵横比",
    "Make first row header": "制作首行标题",
    "Margin (num modules)": "页边距 (num modules)",
    "Master Control Panel": "主控面板",
    "Match": "匹配",
    "Match (regex)": "匹配 (正则表达式)",
    "Max colour value": "最大色值",
    "Max embedded text bytes (iXML/axml/etc)": "最大嵌入文本字节数 (iXML/axml 等)",
    "Max leading letter penalty": "最大首字母惩罚",
    "Max Value": "最大值",
    "Maximum jumps (if jumping backwards)": "最大跳跃(如果向后跳跃)",
    "Memory (KiB)": "内存 (KiB)",
    "Memory factor (r)": "内存系数 (r)",
    "Merge All": "全部合并",
    "Merge delimiter": "合并分隔符",
    "Message": "消息",
    "Message Digest Algorithm": "消息摘要算法",
    "Message format": "消息格式",
    "Method": "方法",
    "Middle rotor": "中间转子",
    "Middle rotor initial value": "中间转子初始值",
    "Middle rotor ring setting": "中间转子环设置",
    "Min colour value": "最小色值",
    "Min Value": "最小值",
    "Minimum File Size": "最小文件大小",
    "Minimum length": "最小长度",
    "Minutes": "分钟",
    "Miscellaneous": "杂项",
    "Mode": "模式",
    "Model": "模型",
    "Module size (px)": "模块大小 (px)",
    "Multiline matching": "多行匹配",
    "Name": "名字",
    "Name (optional)": "名称(可选)",
    "No delimiter": "没有分隔符",
    "Normal Form": "标准形式",
    "Normalise image": "规范化图像",
    "Null preserving": "保留NULL",
    "Number": "数字",
    "Number of bytes": "字节数",
    "Number of dwords to drop": "要丢弃的双字数",
    "Number of horizontal bins": "水平箱数",
    "Number of Integers": "整数个数",
    "Number of vertical bins": "垂直箱数",
    "OCR Engine Mode": "OCR 引擎模式",
    "Offset": "偏移",
    "Offset (IP)": "偏移 (IP)",
    "Only autocrop frames": "只有自动裁剪框架",
    "Only show the subnets": "只显示子网",
    "Opacity (%)": "不透明度 (%)",
    "Opaque background": "不透明背景",
    "Open links in new tab.": "在新标签页中打开链接。",
    "Operating system": "操作系统",
    "Order": "顺序",
    "Output": "输出",
    "Output as": "输出为",
    "Output as hex": "输出十六进制",
    "Output case": "输出大小写",
    "Output Delimiter": "输出分隔符",
    "Output Encoding": "输出编码",
    "Output format": "输出格式",
    "Output Format": "输出格式",
    "Output format string": "输出格式字符串",
    "Output timezone": "输出时区",
    "Output type": "输出类型",
    "Output Type": "输出类型",
    "Output units": "输出单位",
    "Output valid JSON": "输出有效 JSON",
    "Pack radius": "包裹半径",
    "Packed": "已打包",
    "Pad incomplete words": "填入不完整的单词",
    "Padding": "填充",
    "Parallelism": "并行性",
    "Parallelization factor (p)": "并行系数 (p)",
    "Passphrase": "密码",
    "Password": "密码",
    "Password (optional)": "密码(可选)",
    "Pattern": "模式",
    "Pixel Order": "像素顺序",
    "Pixel Scale Factor": "像素比例因子",
    "Pixels per row": "每行像素",
    "Plaintext": "明文",
    "Plugboard": "插件板",
    "PNG Deflate Level": "PNG 压缩水平",
    "PNG Filter Type": "PNG 过滤规则",
    "Point radius": "点半径",
    "Polynomial": "多项式",
    "Position": "位置",
    "Postion": "位置",
    "Precision": "精度",
    "Prefix": "前缀",
    "Preserve comments": "保存 comments",
    "Print amount": "打印数量",
    "Print key": "输出Key",
    "Print spaces between bytes": "打印字节间空格",
    "Private Key": "私钥",
    "Private key of recipient": "接收方私钥",
    "Private key of signer": "签名者私钥",
    "Private key passphrase": "私钥密码",
    "Private key passphrase (optional)": "私钥密码（可选）",
    "Private key password": "私钥密码",
    "Private/Secret Key": "私钥/秘钥",
    "Process": "过程",
    "Program to run": "运行程序",
    "Public key of recipient": "接收方公钥",
    "Public key of signer": "签名者公钥",
    "Public Key X": "公钥 X",
    "Public Key Y": "公钥 Y",
    "Public/Secret Key": "公钥/私钥",
    "Query": "查询",
    "Quotes": "引号",
    "Radius": "半径",
    "Radix": "基数",
    "Range info": "范围信息",
    "Record delimiter": "记录分隔符",
    "Red": "红(Red)",
    "Reflect input": "反射输入",
    "Reflect output": "反射输出",
    "Reflector": "反射器",
    "Reflectors": "反射器",
    "Regex": "正则表达式",
    "Remove excess line breaks": "删除多余的换行符",
    "Remove headers": "移除头部",
    "Remove indentation": "移除缩进",
    "Remove local IPv4 addresses": "移除本地 IPv4 地址",
    "Remove non-alphabet chars": "删除非字母字符",
    "Replace": "替换",
    "Report errors and try to continue": "报告错误并尝试继续",
    "Request Type": "请求类型",
    "Resize buffer after decompression": "解压后调整缓冲区大小",
    "Resizing algorithm": "调整算法",
    "Resolver": "解析器",
    "Restore ://": "还原 ://",
    "Restore [.]": "还原 [.]",
    "Restore hxxp": "还原 hxxp",
    "Result delimiter": "结果分隔符",
    "Return type": "返回类型",
    "Reverse": "反向",
    "Right-hand rotor": "右转子",
    "Right-hand rotor initial value": "右转子初始值",
    "Right-hand rotor ring setting": "右转子环设置",
    "Rotate lower case chars": "轮转小写字母",
    "Rotate numbers": "轮转数字",
    "Rotate upper case chars": "轮转大写字母",
    "Rotation amount (degrees)": "旋转量 (度)",
    "Rounds": "轮数",
    "Row delimiter": "行分隔符",
    "Row delimiters": "行分隔符",
    "RSA Key Length": "RSA 密钥长度",
    "RSA Private Key (PEM)": "RSA 私钥 (PEM)",
    "RSA Public Key (PEM)": "RSA 公钥 (PEM)",
    "Rules": "规则",
    "Sample delimiter": "分隔符样本",
    "Sample length": "样本长度",
    "Sample offset": "样本偏移量",
    "Saturation": "饱和度",
    "Schema (.proto text)": "模式 (.原始文本)",
    "Scheme": "方案",
    "Scope": "范围",
    "Search": "搜索",
    "Search string": "搜索字符串",
    "Seconds": "秒",
    "Section (regex)": "部分(正则表达式)",
    "Seed": "种子",
    "Semicolons before closing braces": "右花括号前的分号",
    "Sentence Delimiter (Regex)": "句子分隔符（正则）",
    "Separator bonus": "分隔符加分",
    "Sequential bonus": "连续加分",
    "Series colours": "系列的颜色",
    "Set key ID (kid) to RFC 7638 thumbprint": "将密钥 ID (kid) 设为 RFC 7638 指纹",
    "Set Total": "设置总数",
    "Show 0%s": "显示 0%s",
    "Show added": "显示新增",
    "Show ASCII": "显示 ASCII",
    "Show confidence": "显示置信度",
    "Show console module messages": "显示控制台模块消息",
    "Show counts": "显示数量",
    "Show instruction hex": "显示指令十六进制",
    "Show instruction position": "显示指令位置",
    "Show metadata": "显示元数据",
    "Show parsed datetime": "显示已解析的日期时间",
    "Show removed": "显示删除",
    "Show response metadata": "显示响应元数据",
    "Show rule warnings": "显示规则警告",
    "Show string lengths": "显示字符串长度",
    "Show strings": "显示字符串",
    "Show subtraction": "显示差集",
    "Show Types": "显示类型",
    "Show Unknown Fields": "显示未知字段",
    "Show variable chars and padding": "显示变量字符和填充",
    "SIGABA mode": "SIGABA 模式",
    "Signature": "签名",
    "Signed": "已签名",
    "Signing algorithm": "签名算法",
    "Size": "大小",
    "Size (bytes)": "大小（字节）",
    "Slow Step": "慢步进",
    "Sort": "排序",
    "Sort Object Keys": "排序对象键",
    "Spaces": "空格",
    "Split delimiter": "分割分隔符",
    "Standard Enigmas": "标准 Enigma",
    "Start": "开始",
    "Start index": "起始索引",
    "Start M37": "开始 M37",
    "Start M61": "开始 M61",
    "Start Χ1": "开始 Χ1",
    "Start Χ2": "开始 Χ2",
    "Start Χ3": "开始 Χ3",
    "Start Χ4": "开始 Χ4",
    "Start Χ5": "开始 Χ5",
    "Start Ψ1": "开始 Ψ1",
    "Start Ψ2": "开始 Ψ2",
    "Start Ψ3": "开始 Ψ3",
    "Start Ψ4": "开始 Ψ4",
    "Start Ψ5": "开始 Ψ5",
    "Starting address (hex)": "起始地址（十六进制）",
    "Starting at": "起始于",
    "Starting index": "起始索引",
    "Stop Words": "停用词",
    "Strict mode": "严格模式",
    "Strict output": "严格输出",
    "Strikethrough": "删除线",
    "Subnet (CIDR)": "子网 (CIDR)",
    "Substitution cost": "替换成本",
    "Support signed values": "支持带符号值",
    "Symmetric autocrop": "对称自动裁切",
    "Tabs": "制表符",
    "Take every": "每隔 N 个取用",
    "Template definition (.handlebars)": "模板定义 (.handlebars)",
    "Threshold": "阈值",
    "Time (ms)": "时间 (ms)",
    "Time Operation": "时间运算",
    "Translation": "翻译",
    "Treat \"+\" as space": "将 \"+\" 视为空格",
    "Treat as UTC": "视作UTC",
    "Truncate octet strings longer than": "截断超过以下长度的八位组字符串",
    "Type": "类型",
    "Type/Key size": "类型/密钥长度",
    "Typex keyboard emulation": "Typex 键盘模拟",
    "Underline": "下划线",
    "Underscore (DMARC, DKIM, etc)": "下划线 (DMARC、DKIM 等)",
    "Unicode support": "Unicode 支持",
    "Unique": "去重",
    "Unit": "单位",
    "Unit type": "单位类型",
    "Units": "单位",
    "UNIX format": "UNIX 格式",
    "Unmappable characters": "无法映射的字符",
    "Unmatched letter penalty": "未匹配字母惩罚",
    "Upper case hex": "大写十六进制",
    "Uppercase hex": "大写十六进制",
    "Use BER": "使用BER",
    "Use checking machine": "使用检查机",
    "Use colour from third column": "使用第三栏的颜色",
    "Use column headers as labels": "使用列标头作为标签",
    "Use low-memory, slower decompression algorithm": "使用低内存、较慢的解压算法",
    "User Key Material": "用户密钥材料",
    "Variant": "变体",
    "Verify result": "校验结果",
    "Vertical align": "垂直对齐",
    "Video": "视频",
    "View TimeStamp": "查看时间戳",
    "Visualisation": "可视化",
    "Wheel Pattern": "轮盘图案",
    "Width": "宽度",
    "Width (bits)": "宽度（位）",
    "Witness Version": "见证版本",
    "Word delimiter": "单词分隔符",
    "Word Delimiter (Regex)": "单词分隔符（正则）",
    "Word length (bytes)": "字长 (字节)",
    "Word Size": "字长",
    "Work factor": "工作因子",
    "X label": "X 标签",
    "X position": "X 位置",
    "X Position": "X 位置",
    "Y label": "Y 标签",
    "Y position": "Y 位置",
    "Y Position": "Y 位置",
    "Zoom Level": "变焦等级",
};
